version: '3.5'

services:
  elasticsearch:
    container_name: dashboard-elasticsearch
    build:
      context: elasticsearch/
    volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx3072m -Xms1024m"
    privileged: true
    cap_add:
    - IPC_LOCK
    - SYS_RESOURCE
    command: bash -c "chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data && su - elasticsearch -c 'elasticsearch'"
    networks:
    - elk
#
#  logstash:
#    build:
#      context: logstash/
#    volumes:
#    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#    - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
#    ports:
#    - "5000:5000"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#    - elk
#    depends_on:
#    - elasticsearch

  kibana:
    container_name: dashboard-kibana
    build:
      context: kibana/
    volumes:
    - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
    - "5601:5601"
    networks:
    - elk
    depends_on:
    - elasticsearch

  nginx:
    container_name: dashboard-nginx
    image: nginx
    restart: always
    volumes:
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    - "443:443"
    networks:
    - elk
    links:
    - elasticsearch
    - kibana
    depends_on:
    - elasticsearch

networks:
  elk:
    name: dashboard-elk
    driver: bridge
